git clone https://github.com/KHAAdotPK/ala_exception.git
git clone https://github.com/KHAAdotPK/allocator.git
git clone https://github.com/KHAAdotPK/String.git
git clone https://github.com/KHAAdotPK/csv.git
git clone https://github.com/KHAAdotPK/Numcy.git
git clone https://github.com/KHAAdotPK/parser.git
git clone https://github.com/KHAAdotPK/sundry.git
git clone https://github.com/KHAAdotPK/Corpus.git
git clone https://github.com/KHAAdotPK/read_write_weights.git
